services:
  app:
    build: .
    ports:
      - "3000:3000"

    environment:
      OLLAMA_BASE_URL: http://ollama:11434

    volumes:
      - ./data:/app/data
      - ./documents:/documents

    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: