services:
  app:
    build: .
    ports:
      - "3000:3000"

    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOCUMENTS_DIRECTORY: /app/data/documents

    volumes:
      - ./data:/app/data

    depends_on:
      - ollama
      - redis

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

  redis:
    image: redis:alpine

volumes:
  ollama: